export interface ColorPalette {
  name: string
  description: string
  colors: {
    name: string
    hex: string
    shades?: { name: string; hex: string }[]
  }[]
}

export const COLOR_PALETTES: ColorPalette[] = [
  {
    name: "Material Design",
    description: "Paleta oficial de Google Material Design",
    colors: [
      {
        name: "Red",
        hex: "#F44336",
        shades: [
          { name: "50", hex: "#FFEBEE" },
          { name: "100", hex: "#FFCDD2" },
          { name: "200", hex: "#EF9A9A" },
          { name: "300", hex: "#E57373" },
          { name: "400", hex: "#EF5350" },
          { name: "500", hex: "#F44336" },
          { name: "600", hex: "#E53935" },
          { name: "700", hex: "#D32F2F" },
          { name: "800", hex: "#C62828" },
          { name: "900", hex: "#B71C1C" },
        ],
      },
      {
        name: "Blue",
        hex: "#2196F3",
        shades: [
          { name: "50", hex: "#E3F2FD" },
          { name: "100", hex: "#BBDEFB" },
          { name: "200", hex: "#90CAF9" },
          { name: "300", hex: "#64B5F6" },
          { name: "400", hex: "#42A5F5" },
          { name: "500", hex: "#2196F3" },
          { name: "600", hex: "#1E88E5" },
          { name: "700", hex: "#1976D2" },
          { name: "800", hex: "#1565C0" },
          { name: "900", hex: "#0D47A1" },
        ],
      },
      {
        name: "Green",
        hex: "#4CAF50",
        shades: [
          { name: "50", hex: "#E8F5E8" },
          { name: "100", hex: "#C8E6C9" },
          { name: "200", hex: "#A5D6A7" },
          { name: "300", hex: "#81C784" },
          { name: "400", hex: "#66BB6A" },
          { name: "500", hex: "#4CAF50" },
          { name: "600", hex: "#43A047" },
          { name: "700", hex: "#388E3C" },
          { name: "800", hex: "#2E7D32" },
          { name: "900", hex: "#1B5E20" },
        ],
      },
      {
        name: "Purple",
        hex: "#9C27B0",
        shades: [
          { name: "50", hex: "#F3E5F5" },
          { name: "100", hex: "#E1BEE7" },
          { name: "200", hex: "#CE93D8" },
          { name: "300", hex: "#BA68C8" },
          { name: "400", hex: "#AB47BC" },
          { name: "500", hex: "#9C27B0" },
          { name: "600", hex: "#8E24AA" },
          { name: "700", hex: "#7B1FA2" },
          { name: "800", hex: "#6A1B9A" },
          { name: "900", hex: "#4A148C" },
        ],
      },
      {
        name: "Orange",
        hex: "#FF9800",
        shades: [
          { name: "50", hex: "#FFF3E0" },
          { name: "100", hex: "#FFE0B2" },
          { name: "200", hex: "#FFCC80" },
          { name: "300", hex: "#FFB74D" },
          { name: "400", hex: "#FFA726" },
          { name: "500", hex: "#FF9800" },
          { name: "600", hex: "#FB8C00" },
          { name: "700", hex: "#F57C00" },
          { name: "800", hex: "#EF6C00" },
          { name: "900", hex: "#E65100" },
        ],
      },
    ],
  },
  {
    name: "Tailwind CSS",
    description: "Paleta de colores de Tailwind CSS",
    colors: [
      {
        name: "Slate",
        hex: "#64748B",
        shades: [
          { name: "50", hex: "#F8FAFC" },
          { name: "100", hex: "#F1F5F9" },
          { name: "200", hex: "#E2E8F0" },
          { name: "300", hex: "#CBD5E1" },
          { name: "400", hex: "#94A3B8" },
          { name: "500", hex: "#64748B" },
          { name: "600", hex: "#475569" },
          { name: "700", hex: "#334155" },
          { name: "800", hex: "#1E293B" },
          { name: "900", hex: "#0F172A" },
        ],
      },
      {
        name: "Blue",
        hex: "#3B82F6",
        shades: [
          { name: "50", hex: "#EFF6FF" },
          { name: "100", hex: "#DBEAFE" },
          { name: "200", hex: "#BFDBFE" },
          { name: "300", hex: "#93C5FD" },
          { name: "400", hex: "#60A5FA" },
          { name: "500", hex: "#3B82F6" },
          { name: "600", hex: "#2563EB" },
          { name: "700", hex: "#1D4ED8" },
          { name: "800", hex: "#1E40AF" },
          { name: "900", hex: "#1E3A8A" },
        ],
      },
      {
        name: "Green",
        hex: "#10B981",
        shades: [
          { name: "50", hex: "#ECFDF5" },
          { name: "100", hex: "#D1FAE5" },
          { name: "200", hex: "#A7F3D0" },
          { name: "300", hex: "#6EE7B7" },
          { name: "400", hex: "#34D399" },
          { name: "500", hex: "#10B981" },
          { name: "600", hex: "#059669" },
          { name: "700", hex: "#047857" },
          { name: "800", hex: "#065F46" },
          { name: "900", hex: "#064E3B" },
        ],
      },
      {
        name: "Purple",
        hex: "#8B5CF6",
        shades: [
          { name: "50", hex: "#FAF5FF" },
          { name: "100", hex: "#F3E8FF" },
          { name: "200", hex: "#E9D5FF" },
          { name: "300", hex: "#D8B4FE" },
          { name: "400", hex: "#C084FC" },
          { name: "500", hex: "#A855F7" },
          { name: "600", hex: "#9333EA" },
          { name: "700", hex: "#7C3AED" },
          { name: "800", hex: "#6D28D9" },
          { name: "900", hex: "#581C87" },
        ],
      },
    ],
  },
  {
    name: "Flat UI",
    description: "Colores planos modernos para interfaces",
    colors: [
      { name: "Turquoise", hex: "#1ABC9C" },
      { name: "Emerald", hex: "#2ECC71" },
      { name: "Peter River", hex: "#3498DB" },
      { name: "Amethyst", hex: "#9B59B6" },
      { name: "Wet Asphalt", hex: "#34495E" },
      { name: "Sun Flower", hex: "#F1C40F" },
      { name: "Carrot", hex: "#E67E22" },
      { name: "Alizarin", hex: "#E74C3C" },
      { name: "Clouds", hex: "#ECF0F1" },
      { name: "Concrete", hex: "#95A5A6" },
    ],
  },
  {
    name: "Pastel",
    description: "Colores suaves y pasteles",
    colors: [
      { name: "Pastel Pink", hex: "#FFD1DC" },
      { name: "Pastel Blue", hex: "#AEC6CF" },
      { name: "Pastel Green", hex: "#77DD77" },
      { name: "Pastel Yellow", hex: "#FDFD96" },
      { name: "Pastel Purple", hex: "#DDA0DD" },
      { name: "Pastel Orange", hex: "#FFB347" },
      { name: "Pastel Red", hex: "#FF6961" },
      { name: "Pastel Mint", hex: "#98FB98" },
      { name: "Pastel Lavender", hex: "#E6E6FA" },
      { name: "Pastel Peach", hex: "#FFCBA4" },
    ],
  },
  {
    name: "Bootstrap",
    description: "Paleta de colores del framework Bootstrap",
    colors: [
      { name: "Primary", hex: "#0D6EFD" },
      { name: "Secondary", hex: "#6C757D" },
      { name: "Success", hex: "#198754" },
      { name: "Danger", hex: "#DC3545" },
      { name: "Warning", hex: "#FFC107" },
      { name: "Info", hex: "#0DCAF0" },
      { name: "Light", hex: "#F8F9FA" },
      { name: "Dark", hex: "#212529" },
    ],
  },
  {
    name: "Ant Design",
    description: "Paleta de colores del sistema de diseño Ant Design",
    colors: [
      {
        name: "Blue",
        hex: "#1890FF",
        shades: [
          { name: "1", hex: "#F0F5FF" },
          { name: "2", hex: "#D6E4FF" },
          { name: "3", hex: "#ADC6FF" },
          { name: "4", hex: "#85A5FF" },
          { name: "5", hex: "#597EF7" },
          { name: "6", hex: "#1890FF" },
          { name: "7", hex: "#096DD9" },
          { name: "8", hex: "#0050B3" },
          { name: "9", hex: "#003A8C" },
          { name: "10", hex: "#002766" },
        ],
      },
      {
        name: "Green",
        hex: "#52C41A",
        shades: [
          { name: "1", hex: "#F6FFED" },
          { name: "2", hex: "#D9F7BE" },
          { name: "3", hex: "#B7EB8F" },
          { name: "4", hex: "#95DE64" },
          { name: "5", hex: "#73D13D" },
          { name: "6", hex: "#52C41A" },
          { name: "7", hex: "#389E0D" },
          { name: "8", hex: "#237804" },
          { name: "9", hex: "#135200" },
          { name: "10", hex: "#092B00" },
        ],
      },
      {
        name: "Red",
        hex: "#FF4D4F",
        shades: [
          { name: "1", hex: "#FFF1F0" },
          { name: "2", hex: "#FFCCC7" },
          { name: "3", hex: "#FFA39E" },
          { name: "4", hex: "#FF7875" },
          { name: "5", hex: "#FF4D4F" },
          { name: "6", hex: "#F5222D" },
          { name: "7", hex: "#CF1322" },
          { name: "8", hex: "#A8071A" },
          { name: "9", hex: "#820014" },
          { name: "10", hex: "#5C0011" },
        ],
      },
    ],
  },
  {
    name: "Nord",
    description: "Paleta de colores Nord inspirada en el Ártico",
    colors: [
      { name: "Polar Night 1", hex: "#2E3440" },
      { name: "Polar Night 2", hex: "#3B4252" },
      { name: "Polar Night 3", hex: "#434C5E" },
      { name: "Polar Night 4", hex: "#4C566A" },
      { name: "Snow Storm 1", hex: "#D8DEE9" },
      { name: "Snow Storm 2", hex: "#E5E9F0" },
      { name: "Snow Storm 3", hex: "#ECEFF4" },
      { name: "Frost 1", hex: "#8FBCBB" },
      { name: "Frost 2", hex: "#88C0D0" },
      { name: "Frost 3", hex: "#81A1C1" },
      { name: "Frost 4", hex: "#5E81AC" },
      { name: "Aurora Red", hex: "#BF616A" },
      { name: "Aurora Orange", hex: "#D08770" },
      { name: "Aurora Yellow", hex: "#EBCB8B" },
      { name: "Aurora Green", hex: "#A3BE8C" },
      { name: "Aurora Purple", hex: "#B48EAD" },
    ],
  },
  {
    name: "Dracula",
    description: "Paleta de colores del tema Dracula",
    colors: [
      { name: "Background", hex: "#282A36" },
      { name: "Current Line", hex: "#44475A" },
      { name: "Selection", hex: "#44475A" },
      { name: "Foreground", hex: "#F8F8F2" },
      { name: "Comment", hex: "#6272A4" },
      { name: "Cyan", hex: "#8BE9FD" },
      { name: "Green", hex: "#50FA7B" },
      { name: "Orange", hex: "#FFB86C" },
      { name: "Pink", hex: "#FF79C6" },
      { name: "Purple", hex: "#BD93F9" },
      { name: "Red", hex: "#FF5555" },
      { name: "Yellow", hex: "#F1FA8C" },
    ],
  },
  {
    name: "One Dark",
    description: "Paleta de colores del tema One Dark",
    colors: [
      { name: "Background", hex: "#282C34" },
      { name: "Foreground", hex: "#ABB2BF" },
      { name: "Red", hex: "#E06C75" },
      { name: "Green", hex: "#98C379" },
      { name: "Yellow", hex: "#E5C07B" },
      { name: "Blue", hex: "#61AFEF" },
      { name: "Purple", hex: "#C678DD" },
      { name: "Cyan", hex: "#56B6C2" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
      { name: "Bright Red", hex: "#BE5046" },
      { name: "Bright Green", hex: "#98C379" },
      { name: "Bright Yellow", hex: "#D19A66" },
      { name: "Bright Blue", hex: "#61AFEF" },
      { name: "Bright Purple", hex: "#C678DD" },
      { name: "Bright Cyan", hex: "#56B6C2" },
    ],
  },
  {
    name: "Solarized",
    description: "Paleta de colores Solarized para desarrollo",
    colors: [
      { name: "Base03", hex: "#002B36" },
      { name: "Base02", hex: "#073642" },
      { name: "Base01", hex: "#586E75" },
      { name: "Base00", hex: "#657B83" },
      { name: "Base0", hex: "#839496" },
      { name: "Base1", hex: "#93A1A1" },
      { name: "Base2", hex: "#EEE8D5" },
      { name: "Base3", hex: "#FDF6E3" },
      { name: "Yellow", hex: "#B58900" },
      { name: "Orange", hex: "#CB4B16" },
      { name: "Red", hex: "#DC322F" },
      { name: "Magenta", hex: "#D33682" },
      { name: "Violet", hex: "#6C71C4" },
      { name: "Blue", hex: "#268BD2" },
      { name: "Cyan", hex: "#2AA198" },
      { name: "Green", hex: "#859900" },
    ],
  },
  {
    name: "Monokai",
    description: "Paleta de colores del tema Monokai",
    colors: [
      { name: "Background", hex: "#272822" },
      { name: "Foreground", hex: "#F8F8F2" },
      { name: "Red", hex: "#F92672" },
      { name: "Orange", hex: "#FD971F" },
      { name: "Yellow", hex: "#E6DB74" },
      { name: "Green", hex: "#A6E22E" },
      { name: "Blue", hex: "#66D9EF" },
      { name: "Purple", hex: "#AE81FF" },
      { name: "Brown", hex: "#75715E" },
      { name: "White", hex: "#F8F8F2" },
      { name: "Light Gray", hex: "#CCCCCC" },
      { name: "Dark Gray", hex: "#888888" },
    ],
  },
  {
    name: "Gruvbox",
    description: "Paleta de colores retro groove Gruvbox",
    colors: [
      { name: "Dark0 Hard", hex: "#1D2021" },
      { name: "Dark0", hex: "#282828" },
      { name: "Dark0 Soft", hex: "#32302F" },
      { name: "Dark1", hex: "#3C3836" },
      { name: "Dark2", hex: "#504945" },
      { name: "Dark3", hex: "#665C54" },
      { name: "Dark4", hex: "#7C6F64" },
      { name: "Light0 Hard", hex: "#F9F5D7" },
      { name: "Light0", hex: "#FBF1C7" },
      { name: "Light0 Soft", hex: "#F2E5BC" },
      { name: "Light1", hex: "#EBDBB2" },
      { name: "Light2", hex: "#D5C4A1" },
      { name: "Light3", hex: "#BDAE93" },
      { name: "Light4", hex: "#A89984" },
      { name: "Bright Red", hex: "#FB4934" },
      { name: "Bright Green", hex: "#B8BB26" },
      { name: "Bright Yellow", hex: "#FABD2F" },
      { name: "Bright Blue", hex: "#83A598" },
      { name: "Bright Purple", hex: "#D3869B" },
      { name: "Bright Aqua", hex: "#8EC07C" },
      { name: "Bright Orange", hex: "#FE8019" },
    ],
  },
  {
    name: "Tokyo Night",
    description: "Paleta de colores inspirada en la noche de Tokio",
    colors: [
      { name: "Background", hex: "#1A1B26" },
      { name: "Background Dark", hex: "#16161E" },
      { name: "Background Highlight", hex: "#292E42" },
      { name: "Terminal Black", hex: "#414868" },
      { name: "Foreground", hex: "#C0CAF5" },
      { name: "Foreground Dark", hex: "#A9B1D6" },
      { name: "Red", hex: "#F7768E" },
      { name: "Orange", hex: "#FF9E64" },
      { name: "Yellow", hex: "#E0AF68" },
      { name: "Green", hex: "#9ECE6A" },
      { name: "Teal", hex: "#73DACA" },
      { name: "Blue", hex: "#7AA2F7" },
      { name: "Purple", hex: "#BB9AF7" },
      { name: "Magenta", hex: "#C0CAF5" },
    ],
  },
  {
    name: "Catppuccin",
    description: "Paleta de colores suave y cálida Catppuccin",
    colors: [
      { name: "Rosewater", hex: "#F5E0DC" },
      { name: "Flamingo", hex: "#F2CDCD" },
      { name: "Pink", hex: "#F5C2E7" },
      { name: "Mauve", hex: "#CBA6F7" },
      { name: "Red", hex: "#F38BA8" },
      { name: "Maroon", hex: "#EBA0AC" },
      { name: "Peach", hex: "#FAB387" },
      { name: "Yellow", hex: "#F9E2AF" },
      { name: "Green", hex: "#A6E3A1" },
      { name: "Teal", hex: "#94E2D5" },
      { name: "Sky", hex: "#89DCEB" },
      { name: "Sapphire", hex: "#74C7EC" },
      { name: "Blue", hex: "#89B4FA" },
      { name: "Lavender", hex: "#B4BEFE" },
      { name: "Text", hex: "#CDD6F4" },
      { name: "Subtext1", hex: "#BAC2DE" },
      { name: "Subtext0", hex: "#A6ADC8" },
      { name: "Overlay2", hex: "#9399B2" },
      { name: "Overlay1", hex: "#7F849C" },
      { name: "Overlay0", hex: "#6C7086" },
      { name: "Surface2", hex: "#585B70" },
      { name: "Surface1", hex: "#45475A" },
      { name: "Surface0", hex: "#313244" },
      { name: "Base", hex: "#1E1E2E" },
      { name: "Mantle", hex: "#181825" },
      { name: "Crust", hex: "#11111B" },
    ],
  },
  {
    name: "Vintage",
    description: "Colores vintage y retro",
    colors: [
      { name: "Dusty Rose", hex: "#D4A574" },
      { name: "Sage Green", hex: "#9CAF88" },
      { name: "Burnt Orange", hex: "#CC8963" },
      { name: "Mustard Yellow", hex: "#E4B429" },
      { name: "Dusty Blue", hex: "#7A9CC6" },
      { name: "Mauve", hex: "#B19CD9" },
      { name: "Terracotta", hex: "#C65D07" },
      { name: "Olive", hex: "#8B966D" },
      { name: "Burgundy", hex: "#722F37" },
      { name: "Cream", hex: "#F7F3E9" },
    ],
  },
  {
    name: "Neon",
    description: "Colores neón vibrantes y llamativos",
    colors: [
      { name: "Electric Blue", hex: "#00FFFF" },
      { name: "Hot Pink", hex: "#FF1493" },
      { name: "Lime Green", hex: "#32CD32" },
      { name: "Electric Purple", hex: "#BF00FF" },
      { name: "Neon Orange", hex: "#FF4500" },
      { name: "Electric Yellow", hex: "#FFFF00" },
      { name: "Neon Red", hex: "#FF073A" },
      { name: "Electric Green", hex: "#00FF00" },
      { name: "Cyber Purple", hex: "#8A2BE2" },
      { name: "Neon Mint", hex: "#00FF7F" },
    ],
  },
  {
    name: "Earth Tones",
    description: "Tonos tierra naturales y orgánicos",
    colors: [
      { name: "Forest Green", hex: "#355E3B" },
      { name: "Sienna", hex: "#A0522D" },
      { name: "Umber", hex: "#6F4E37" },
      { name: "Ochre", hex: "#CC7722" },
      { name: "Moss Green", hex: "#8A9A5B" },
      { name: "Clay", hex: "#B66A50" },
      { name: "Sand", hex: "#C2B280" },
      { name: "Stone Gray", hex: "#928E85" },
      { name: "Bark Brown", hex: "#8B4513" },
      { name: "Sage", hex: "#87AE73" },
    ],
  },
  {
    name: "Ocean",
    description: "Colores inspirados en el océano",
    colors: [
      { name: "Deep Sea", hex: "#003366" },
      { name: "Ocean Blue", hex: "#006994" },
      { name: "Turquoise", hex: "#40E0D0" },
      { name: "Seafoam", hex: "#71EEB8" },
      { name: "Coral", hex: "#FF7F50" },
      { name: "Pearl", hex: "#F0EAD6" },
      { name: "Seaweed", hex: "#2E8B57" },
      { name: "Wave", hex: "#4682B4" },
      { name: "Tide Pool", hex: "#008B8B" },
      { name: "Sand Dollar", hex: "#F5DEB3" },
    ],
  },
]
